export enum ACTIONS {
    ACTION_RECEIVER = 'ACTION_RECEIVER',
    DIRECTORY_OPEN = 'DIRECTORY_OPEN',
    DIRECTORY_SELECTED = 'DIRECTORY_SELECTED',
    SYNC_START = 'SYNC_START',
    SYNC_INPROGRESS = 'SYNC_INPROGRESS',
    SYNC_COMPLETE = 'SYNC_COMPLETE',
    SYNC_KILL = 'SYNC_KILL'
}